require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NegociationsController do

  # This should return the minimal set of attributes required to create a valid
  # Negociation. As you add validations to Negociation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NegociationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end
  
  before (:each) do
    @negociation = FactoryGirl.create(:negociation)
    @user = FactoryGirl.create(:user)
    sign_in @user
  end

  describe "GET index" do
    it "assigns all negociations as @negociations" do
      get :index, {}
      assigns(:negociations).should eq([@negociation])
    end
  end

  describe "GET show" do
    it "assigns the requested negociation as @negociation" do
      get :show, {:id => @negociation.to_param}
      assigns(:negociation).should eq(@negociation)
    end
  end

  describe "GET new" do
    it "assigns a new negociation as @negociation" do
      get :new, {}
      assigns(:negociation).should be_a_new(Negociation)
    end
  end

  describe "GET edit" do
    it "assigns the requested negociation as @negociation" do
      get :edit, {:id => @negociation.to_param}
      assigns(:negociation).should eq(@negociation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Negociation" do
        expect {
          post :create, {:negociation => valid_attributes}
        }.to change(Negociation, :count).by(1)
      end

      it "assigns a newly created negociation as @negociation" do
        post :create, {:negociation => valid_attributes}
        assigns(:negociation).should be_a(Negociation)
        assigns(:negociation).should be_persisted
      end

      it "redirects to the offering path" do
        post :create, {:negociation => valid_attributes}
        response.should redirect_to(offerings_path + "/")
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved negociation as @negociation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Negociation.any_instance.stub(:save).and_return(false)
        post :create, {:negociation => {}}
        assigns(:negociation).should be_a_new(Negociation)
      end

      it "go to the offering path" do
        # Trigger the behavior that occurs when invalid params are submitted
        Negociation.any_instance.stub(:save).and_return(false)
        post :create, {:negociation => {}}
        response.should redirect_to(offerings_path + "/")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested negociation" do
        negociation = Negociation.create! valid_attributes
        # Assuming there are no other negociations in the database, this
        # specifies that the Negociation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Negociation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => negociation.to_param, :negociation => {'these' => 'params'}}
      end

      it "assigns the requested negociation as @negociation" do
        negociation = Negociation.create! valid_attributes
        put :update, {:id => negociation.to_param, :negociation => valid_attributes}
        assigns(:negociation).should eq(negociation)
      end

      it "redirects to the negociation" do
        negociation = Negociation.create! valid_attributes
        put :update, {:id => negociation.to_param, :negociation => valid_attributes}
        response.should redirect_to(negociation)
      end
    end

    describe "with invalid params" do
      it "assigns the negociation as @negociation" do
        negociation = Negociation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Negociation.any_instance.stub(:save).and_return(false)
        put :update, {:id => negociation.to_param, :negociation => {}}
        assigns(:negociation).should eq(negociation)
      end

      it "re-renders the 'edit' template" do
        negociation = Negociation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Negociation.any_instance.stub(:save).and_return(false)
        put :update, {:id => negociation.to_param, :negociation => {}}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested negociation" do
      negociation = Negociation.create! valid_attributes
      expect {
        delete :destroy, {:id => negociation.to_param}
      }.to change(Negociation, :count).by(-1)
    end

    it "redirects to the negociations list" do
      negociation = Negociation.create! valid_attributes
      delete :destroy, {:id => negociation.to_param}
      response.should redirect_to(negociations_url)
    end
  end

end
